- hosts: graylog
  tasks:
    - name: set timezone UTC
      ansible.builtin.shell: |
        timedatectl set-timezone UTC

    - name: add libssl repo
      apt_repository:
        repo: 'deb http://security.ubuntu.com/ubuntu focal-security main'
        state: present


    - name: update package lists
      apt:
        update_cache: yes

    - name: install packages
      apt:
        name: 
          - wget
          - curl
          - gnupg
          - libssl1.1
        state: present

    - name: Creates directory
      ansible.builtin.file:
        path: /opt/graylog
        state: directory



    - name: Copy elasticsearch to remote host
      copy:
        src: ./elasticsearch-7.10.2-amd64.deb
        dest: /opt/graylog/elasticsearch-7.10.2-amd64.deb 
        force: no

    - name: Copy mongodb to remote host
      copy:
        src: ./mongodb-org-server_5.0.23_amd64.deb
        dest: /opt/graylog/mongodb-org-server_5.0.23_amd64.deb
        force: no


    - name: Copy graylog to remote host
      copy:
        src: ./graylog-server_5.1.10-1_amd64.deb
        dest: /opt/graylog/graylog-server_5.1.10-1_amd64.deb
        force: no

    - name: install packages
      apt:
        deb: "{{ item }}" 
        state: present
      loop:
        - /opt/graylog/elasticsearch-7.10.2-amd64.deb 
        - /opt/graylog/mongodb-org-server_5.0.23_amd64.deb
        - /opt/graylog/graylog-server_5.1.10-1_amd64.deb

    # - name: set cluster name
    #   ansible.builtin.lineinfile:
    #     path: /etc/elasticsearch/elasticsearch.yml
    #     regexp: '^#cluster.name: my-application'
    #     line: 'cluster.name: graylog-cluster'

    # - name: change node
    #   ansible.builtin.lineinfile:
    #     path: /etc/elasticsearch/elasticsearch.yml
    #     regexp: '^#node.name: $hostname'
    #     line: 'node.name: {{ ansible_hostname }}'